spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.99.106.79/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wxcd232f22e6dff849
  mpAppSecret: dd4bb14233cde28b147f1a8d960495a6
